#!/bin/bash

# DIR="requirements/roles/"
# # init
# # look for empty directory
# if [ -d "$DIR" ]
# then
# 	if [ "$(ls -A $DIR)" ]; then
#         echo "Do nothing"
# 	else
#         # Install custom playbooks dependencies
#         ansible-galaxy install \
#             --force \
#             --roles-path="requirements/roles/" \
#             --role-file="install-requirements.yml"
#             # --roles-path="$MOLECULE_SCENARIO_NAME/requirements/roles/"
# 	fi
# else
# 	echo "Directory $DIR not found."
#   exit 1
# fi

# Install custom playbooks dependencies
ansible-galaxy install \
    --force \
    --roles-path="roles/" \
    --role-file="install-requirements.yml"
